"use client";

// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { RecoilRoot } from "recoil";
import Analytics from "@/components/analytics";
import { GoogleTagManager } from '@next/third-parties/google'

// import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "App",
//   description: "Generated by create next app",
// };GTM-5RW3QBMN

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <Analytics />
        {/* <GoogleTagManager gtmId="GTM-5RW3QBMN" /> */}

        <RecoilRoot>
          {/* <Suspense fallback={<div>loading...</div>}>{children}</Suspense> */}
          {children}
        </RecoilRoot>
      </body>
    </html>
  );
}
